#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("learn.Resource", IsApplication=true)]

namespace learn
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f080000
			public const int androidcolors = 2131230720;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int adSize = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int adSizes = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int adUnitId = 2130771973;
			
			// aapt resource value: 0x7f010002
			public const int circleCrop = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int imageAspectRatio = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int imageAspectRatioAdjust = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070010
			public const int black = 2131165200;
			
			// aapt resource value: 0x7f070000
			public const int black_overlay = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int blue = 2131165185;
			
			// aapt resource value: 0x7f07000b
			public const int customeblue = 2131165195;
			
			// aapt resource value: 0x7f070006
			public const int darkblue = 2131165190;
			
			// aapt resource value: 0x7f070008
			public const int darkgreen = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int darkorange = 2131165193;
			
			// aapt resource value: 0x7f070007
			public const int darkpurple = 2131165191;
			
			// aapt resource value: 0x7f07000a
			public const int darkred = 2131165194;
			
			// aapt resource value: 0x7f070003
			public const int green = 2131165187;
			
			// aapt resource value: 0x7f07000c
			public const int lowDarkfont = 2131165196;
			
			// aapt resource value: 0x7f070004
			public const int orange = 2131165188;
			
			// aapt resource value: 0x7f070002
			public const int purple = 2131165186;
			
			// aapt resource value: 0x7f070005
			public const int red = 2131165189;
			
			// aapt resource value: 0x7f07000d
			public const int white = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int whiteback = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int whitebackground = 2131165199;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int backgroundbtn = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int backgroundbtnCopy = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int btn = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int home = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int houseicon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int mosa = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090038
			public const int a = 2131296312;
			
			// aapt resource value: 0x7f090003
			public const int adView1 = 2131296259;
			
			// aapt resource value: 0x7f090000
			public const int adjust_height = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int adjust_width = 2131296257;
			
			// aapt resource value: 0x7f090039
			public const int b = 2131296313;
			
			// aapt resource value: 0x7f090005
			public const int b1 = 2131296261;
			
			// aapt resource value: 0x7f09000f
			public const int b10 = 2131296271;
			
			// aapt resource value: 0x7f090010
			public const int b11 = 2131296272;
			
			// aapt resource value: 0x7f090011
			public const int b12 = 2131296273;
			
			// aapt resource value: 0x7f090012
			public const int b13 = 2131296274;
			
			// aapt resource value: 0x7f090013
			public const int b14 = 2131296275;
			
			// aapt resource value: 0x7f090014
			public const int b15 = 2131296276;
			
			// aapt resource value: 0x7f090015
			public const int b16 = 2131296277;
			
			// aapt resource value: 0x7f090016
			public const int b17 = 2131296278;
			
			// aapt resource value: 0x7f090017
			public const int b18 = 2131296279;
			
			// aapt resource value: 0x7f090018
			public const int b19 = 2131296280;
			
			// aapt resource value: 0x7f090007
			public const int b2 = 2131296263;
			
			// aapt resource value: 0x7f090019
			public const int b20 = 2131296281;
			
			// aapt resource value: 0x7f09001a
			public const int b21 = 2131296282;
			
			// aapt resource value: 0x7f09001b
			public const int b22 = 2131296283;
			
			// aapt resource value: 0x7f09001c
			public const int b23 = 2131296284;
			
			// aapt resource value: 0x7f09001d
			public const int b24 = 2131296285;
			
			// aapt resource value: 0x7f09001e
			public const int b25 = 2131296286;
			
			// aapt resource value: 0x7f09001f
			public const int b26 = 2131296287;
			
			// aapt resource value: 0x7f090020
			public const int b27 = 2131296288;
			
			// aapt resource value: 0x7f090021
			public const int b28 = 2131296289;
			
			// aapt resource value: 0x7f090022
			public const int b29 = 2131296290;
			
			// aapt resource value: 0x7f090008
			public const int b3 = 2131296264;
			
			// aapt resource value: 0x7f090023
			public const int b30 = 2131296291;
			
			// aapt resource value: 0x7f090024
			public const int b31 = 2131296292;
			
			// aapt resource value: 0x7f090025
			public const int b32 = 2131296293;
			
			// aapt resource value: 0x7f090026
			public const int b33 = 2131296294;
			
			// aapt resource value: 0x7f090027
			public const int b34 = 2131296295;
			
			// aapt resource value: 0x7f090028
			public const int b35 = 2131296296;
			
			// aapt resource value: 0x7f090029
			public const int b36 = 2131296297;
			
			// aapt resource value: 0x7f09002a
			public const int b37 = 2131296298;
			
			// aapt resource value: 0x7f09002b
			public const int b38 = 2131296299;
			
			// aapt resource value: 0x7f09002c
			public const int b39 = 2131296300;
			
			// aapt resource value: 0x7f090009
			public const int b4 = 2131296265;
			
			// aapt resource value: 0x7f09002d
			public const int b40 = 2131296301;
			
			// aapt resource value: 0x7f09002e
			public const int b41 = 2131296302;
			
			// aapt resource value: 0x7f09002f
			public const int b42 = 2131296303;
			
			// aapt resource value: 0x7f090030
			public const int b43 = 2131296304;
			
			// aapt resource value: 0x7f090031
			public const int b44 = 2131296305;
			
			// aapt resource value: 0x7f090032
			public const int b45 = 2131296306;
			
			// aapt resource value: 0x7f090033
			public const int b46 = 2131296307;
			
			// aapt resource value: 0x7f090034
			public const int b47 = 2131296308;
			
			// aapt resource value: 0x7f090035
			public const int b48 = 2131296309;
			
			// aapt resource value: 0x7f090036
			public const int b49 = 2131296310;
			
			// aapt resource value: 0x7f09000a
			public const int b5 = 2131296266;
			
			// aapt resource value: 0x7f090037
			public const int b50 = 2131296311;
			
			// aapt resource value: 0x7f09000b
			public const int b6 = 2131296267;
			
			// aapt resource value: 0x7f09000c
			public const int b7 = 2131296268;
			
			// aapt resource value: 0x7f09000d
			public const int b8 = 2131296269;
			
			// aapt resource value: 0x7f09000e
			public const int b9 = 2131296270;
			
			// aapt resource value: 0x7f090066
			public const int btnSpeak = 2131296358;
			
			// aapt resource value: 0x7f09005f
			public const int btninfo = 2131296351;
			
			// aapt resource value: 0x7f090064
			public const int btnletters = 2131296356;
			
			// aapt resource value: 0x7f090061
			public const int btnrate = 2131296353;
			
			// aapt resource value: 0x7f09005e
			public const int btnstart = 2131296350;
			
			// aapt resource value: 0x7f090063
			public const int btnus = 2131296355;
			
			// aapt resource value: 0x7f090065
			public const int btnwords = 2131296357;
			
			// aapt resource value: 0x7f09003a
			public const int c = 2131296314;
			
			// aapt resource value: 0x7f09003b
			public const int d = 2131296315;
			
			// aapt resource value: 0x7f09003c
			public const int e = 2131296316;
			
			// aapt resource value: 0x7f090067
			public const int editSpeech = 2131296359;
			
			// aapt resource value: 0x7f090059
			public const int eight = 2131296345;
			
			// aapt resource value: 0x7f09003d
			public const int f = 2131296317;
			
			// aapt resource value: 0x7f090056
			public const int five = 2131296342;
			
			// aapt resource value: 0x7f090055
			public const int four = 2131296341;
			
			// aapt resource value: 0x7f09003e
			public const int g = 2131296318;
			
			// aapt resource value: 0x7f09003f
			public const int h = 2131296319;
			
			// aapt resource value: 0x7f090068
			public const int home = 2131296360;
			
			// aapt resource value: 0x7f09006c
			public const int hospital = 2131296364;
			
			// aapt resource value: 0x7f090040
			public const int i = 2131296320;
			
			// aapt resource value: 0x7f090041
			public const int j = 2131296321;
			
			// aapt resource value: 0x7f090042
			public const int k = 2131296322;
			
			// aapt resource value: 0x7f090043
			public const int l = 2131296323;
			
			// aapt resource value: 0x7f09005d
			public const int linearLayout1 = 2131296349;
			
			// aapt resource value: 0x7f090044
			public const int m = 2131296324;
			
			// aapt resource value: 0x7f090045
			public const int n = 2131296325;
			
			// aapt resource value: 0x7f09005a
			public const int nine = 2131296346;
			
			// aapt resource value: 0x7f090002
			public const int none = 2131296258;
			
			// aapt resource value: 0x7f090046
			public const int o = 2131296326;
			
			// aapt resource value: 0x7f090052
			public const int one = 2131296338;
			
			// aapt resource value: 0x7f090047
			public const int p = 2131296327;
			
			// aapt resource value: 0x7f090048
			public const int q = 2131296328;
			
			// aapt resource value: 0x7f090049
			public const int r = 2131296329;
			
			// aapt resource value: 0x7f09004a
			public const int s = 2131296330;
			
			// aapt resource value: 0x7f090069
			public const int school = 2131296361;
			
			// aapt resource value: 0x7f09005c
			public const int scrollView1 = 2131296348;
			
			// aapt resource value: 0x7f09006d
			public const int sea = 2131296365;
			
			// aapt resource value: 0x7f090058
			public const int seven = 2131296344;
			
			// aapt resource value: 0x7f090057
			public const int six = 2131296343;
			
			// aapt resource value: 0x7f09006e
			public const int sport = 2131296366;
			
			// aapt resource value: 0x7f09006b
			public const int street = 2131296363;
			
			// aapt resource value: 0x7f09004b
			public const int t = 2131296331;
			
			// aapt resource value: 0x7f09005b
			public const int ten = 2131296347;
			
			// aapt resource value: 0x7f090004
			public const int textView1 = 2131296260;
			
			// aapt resource value: 0x7f090006
			public const int textView2 = 2131296262;
			
			// aapt resource value: 0x7f090060
			public const int textView3 = 2131296352;
			
			// aapt resource value: 0x7f090062
			public const int textView4 = 2131296354;
			
			// aapt resource value: 0x7f090054
			public const int three = 2131296340;
			
			// aapt resource value: 0x7f090053
			public const int two = 2131296339;
			
			// aapt resource value: 0x7f09004c
			public const int u = 2131296332;
			
			// aapt resource value: 0x7f09004d
			public const int v = 2131296333;
			
			// aapt resource value: 0x7f09004e
			public const int w = 2131296334;
			
			// aapt resource value: 0x7f09006a
			public const int work = 2131296362;
			
			// aapt resource value: 0x7f09004f
			public const int x = 2131296335;
			
			// aapt resource value: 0x7f090050
			public const int y = 2131296336;
			
			// aapt resource value: 0x7f090051
			public const int z = 2131296337;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f050000
			public const int google_play_services_version = 2131034112;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int help = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int home = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int hospital = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int letters = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int school = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int sea = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int select = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int speak = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int sport = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int street = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int words = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int work = 2130903052;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f04000a
			public const int Banner_Ads = 2130968586;
			
			// aapt resource value: 0x7f040005
			public const int accept = 2130968581;
			
			// aapt resource value: 0x7f040009
			public const int app_name = 2130968585;
			
			// aapt resource value: 0x7f040001
			public const int auth_google_play_services_client_facebook_display_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int auth_google_play_services_client_google_display_name = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int common_google_play_services_unknown_issue = 2130968578;
			
			// aapt resource value: 0x7f040008
			public const int create_calendar_message = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int create_calendar_title = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int decline = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int store_picture_message = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int store_picture_title = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int MyCustomTheme = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Theme_IAPTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AdsAttrs = new int[] {
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int AdsAttrs_adSize = 0;
			
			// aapt resource value: 1
			public const int AdsAttrs_adSizes = 1;
			
			// aapt resource value: 2
			public const int AdsAttrs_adUnitId = 2;
			
			public static int[] LoadingImageView = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
